name: dating_your_date
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ^3.1.0
  
dependencies: 
  flutter: 
    sdk: flutter
  flutter_launcher_icons:
  cached_network_image:
  flutter_svg: 
  flutter_svg_provider:
  flutter_verification_code:
  intl: 
  google_fonts:
  postgres: 
  shared_preferences:
  protobuf:
  grpc:
  protoc_plugin:
  uuid:
  dropdown_button2:
  flutter_secure_storage:


flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: "assets/images/app_logo.png"
  image_path_ios: "assets/images/app_logo.png"
  android_icon_background: "#FFFFFF"
  ios_icon_background: "#FFFFFF"

# run command to using ： flutter pub run flutter_launcher_icons:main

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Rounded Mplus 1c
      fonts: 
        - asset: assets/fonts/RoundedMplus1cRegular.ttf
          weight: 400
    - family: Montserrat
      fonts: 
        - asset: assets/fonts/MontserratSemiBold.ttf
          weight: 600
    - family: SF Pro Text
      fonts: 
        - asset: assets/fonts/SFProTextLight.ttf
          weight: 300
        - asset: assets/fonts/SFProTextRegular.ttf
          weight: 400
